### PR TITLE
Upgrade to allow suitably smooth on-ramp use of this starter template

### PR DESCRIPTION
**Pull request by narration-sd**
This PR, fully integrated and tested with the current fully working @sanity/astro,  was inspired by what became a full-week session with an evidently experienced and capable, designer-focused developer, who was utterly blocked by the intricacies of the original package. 

The result of upgrades to solve this is entirely in the spirit of Astro's own approach to TypeScript, fully implementing its ability to be used at any level of strictness, but not requiring this until a person may wish to do so.  

As the revised Readme describes, there's also an addition to make nicely wrap-formatted images available embedded in Portable Text, to facilitate expectations of those who come over from platforms like WordPress. 

You can see it operating [here, on Vercel.](https://sanity-template-astro-clean-brown.vercel.app/), and others in the Sanity arena have found it to 'just work', with the nice appearance extended, in the line as this starter originally intended. 

Astro 4 ability is now included, up-to-date along with all other dependencies.

You'll note that in the Readme update, I've suggested the original heavy-TypeScript version be included on a branch, sans the script which soon became ineffective at down-conversion, and would always become so. This is in courtesy to the originators; personally I'm not sure it's a best idea, so especially listening for what you'd prefer. There could instead be just a reference respecting the original.

Will put this up in fully approval-ready form as soon as that underlying PR #140 can find its approval, and according with your comments here.

### CODE REVIEW

**Comment by narration-sd** [comment]
...disabled actions on the source of this PR; apologies for the attempted runs....

**Comment by narration-sd** [comment]
While doing the small upgrades after Snyk noticed about licensing, I found there's an introductory Sanity doc page, which I should be able update easily on its own PR as this one becomes approved, as it gets its text from the Readme which has already been updated here.

**Comment by OliverSpeir** [comment]
@narration-sd  Thanks for this fantastic work 

Hope to see this merged

**Comment by narration-sd** [comment]
@OliverSpeir  thanks :) , and I'm on this, due to the very appreciated move of @stipsan today , who approved the fix enabling the official @sanity/astro package!

**Comment by narration-sd** [comment]
This PR should now be ready for approval.  I've brought in the newly released @sanity/astro with its fix, and updated the README for this, also with some edits to improve.

I enabled Snyk on my repo, but this doesn't show a license issue, which I imagine is tied to a specific Sanity configuration. The license and its specification in the package.json seem to look fine, so please let me know if I need to change anything to pass the check - will do such immediately.

Thanks, and it will be very nice to see this upgrade on its way. I believe the 'smooth onramp' approach is very desirable for Sanity and Astro, as explained above, and as you can see, desire for it is showing :)

All of this work stands behind Sanity Astro Presentation, as intended, and that project is going quite well, soon I suspect to become more visible.

**Comment by narration-sd** [comment]
updated all to latest via ncu -u, through Astro 4.4.1; as anticipated, no problems

**Comment by OliverSpeir** [comment]
sanity/astro 3 is out now 🎉

**Comment by OliverSpeir** [comment]
Any update on this @sjelfull @kmelve @narration-sd ?

**Comment by kmelve** [comment]
We will soon roll out updates to both the integration and the starters to better accommodate Visual Editing.

Although we greatly appreciate the efforts that went into this PR, we can't merge it pending these updates. Stay tuned! 

(Of course, you're welcome to fork this template and submit as your own to sanity.io/templates!)

**Comment by narration-sd** [comment]
> Any update on this @sjelfull @kmelve @narration-sd ?

Hi Oliver, actually I have a small improvement to bring over from a project using this; will do and let you know.

**Pull request closed without merging**
